// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZaizaiDate.Database.DatabaseContext;

namespace ZaizaiDate.Database.Migration.Migrations
{
    [DbContext(typeof(ZaiZaiDateDbContext))]
    partial class ZaiZaiDateDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");
#pragma warning restore 612, 618
        }
    }
}
